# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

env:
  # Disable Go modules so we can format and lint loose Go files.
  GO111MODULE: off

tasks:
  format:
    desc: Run all format tasks
    cmd: task format:go format:py

  lint:
    desc: Run all lint tasks
    cmd: task lint:go lint:py

  check:
    desc: Run all check tasks
    cmd: task check:go check:py

  # Go-related tasks
  format:go:
    desc: Formats Go code
    cmd: go fmt ./...

  lint:go:
    desc: Lints Go code
    cmd: go vet ./...

  check:go:
    desc: Formats and lints Go code
    cmd: task format:go lint:go

  # Python-related tasks
  format:py:
    desc: Formats Python code
    cmd: ruff format . --line-length 80

  lint:py:
    desc: Lints Python code
    cmd: ruff check .

  check:py:
    desc: Formats and lints Python code
    cmd: task format:py lint:py
