# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  # Go-related tasks
  format:go:
    desc: Formats Go code
    cmd: gofmt -w .

  # Python-related tasks
  format:py:
    desc: Formats Python code
    cmd: ruff format .
