# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

tasks:
  format:
    desc: Run all format tasks
    cmds:
      - task format:go
      - task format:py

  lint:
    desc: Run all lint tasks
    cmds:
      - task lint:go
      - task lint:py

  check:
    desc: Run all check tasks
    cmds:
      - task check:py

  # Go-related tasks
  format:go:
    desc: Formats Go code
    cmd: GO111MODULE=off go fmt ./...

  lint:go:
    desc: Lints Go code
    cmd: GO111MODULE=off go vet ./...

  # Python-related tasks
  format:py:
    desc: Formats Python code
    cmd: ruff format . --line-length 80

  lint:py:
    desc: Lints Python code
    cmd: ruff check .

  check:py:
    desc: Formats and lints Python code
    cmds:
      - task format:py
      - task lint:py
